# Generated by Django 5.1.3 on 2024-11-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermarketrates',
            old_name='expire_on',
            new_name='expired_on',
        ),
    ]
